services:
  frontend:
    build: .
    container_name: tasked-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - VITE_PB_URL="http://localhost:8091"

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: tasked-pocketbase
    ports:
      - "8091:8091"
    volumes:
      - ./pb_data:/pb_data
    restart: unless-stopped

volumes:
  pb_data:
